# Generated by Django 5.2.5 on 2025-09-29 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_url', models.URLField(help_text='Link do publicznego kalendarza')),
                ('calendar_name', models.CharField(help_text='Nazwa kalendarza (opcjonalnie)', max_length=100)),
                ('owner_name', models.CharField(blank=True, help_text='Nazwa właściciela', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('calendar_token', models.CharField(blank=True, editable=False, max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'calendar_token')},
            },
        ),
    ]
