# Generated by Django 5.2.5 on 2025-10-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_favoritecalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numer telefonu'),
        ),
    ]
