# Generated by Django 5.2.5 on 2025-09-11 13:23

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='share_token',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=12, unique=True),
        ),
    ]
