# Generated by Django 5.2.5 on 2025-09-19 08:55

import myschedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschedule', '0002_alter_calendar_share_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='share_token',
            field=models.CharField(default=myschedule.models.generate_share_token, editable=False, max_length=12, unique=True),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('calendar', 'date', 'start_time', 'end_time'), name='unique_availability'),
        ),
    ]
