# Generated by Django 5.2.5 on 2025-09-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschedule', '0003_alter_calendar_share_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RemoveConstraint(
            model_name='availability',
            name='unique_availability',
        ),
    ]
