# Generated by Django 5.2.5 on 2025-09-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschedule', '0004_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='start_time_before_end_time'),
        ),
    ]
