# Generated by Django 5.2.5 on 2025-10-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschedule', '0005_availability_start_time_before_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email klienta'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_note',
            field=models.TextField(blank=True, help_text='Dodatkowe informacje od klienta', verbose_name='Notatka klienta'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon klienta'),
        ),
    ]
